pipeline {
    agent any
    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/SoniyaRam/EmploeeDemo.git'
            }
        }
        stage('Build') {
            steps {
                sh './mvnw clean package -DskipTests'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t spring-boot-docker .'
            }
        }
        stage('Run Docker Container') {
            steps {
                sh '''
                  docker stop spring-app || true
                  docker rm spring-app || true
                  docker run -d --name spring-app -p 8080:8080 spring-boot-docker
                '''
            }
        }
    }
}
